name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    types:
      - opened

jobs:
  build:
    strategy:
        matrix:
          go-version: [ 1.20.x, 1.21.x ]
          platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          install-mode: "goinstall"

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
